#Variables
@baseUrl = http://localhost:3333

# @name Healthcheck
GET  {{baseUrl}}/health

###

# @name getRooms
GET {{baseUrl}}/rooms

### 

# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "sala-test3",
  "description": "test3"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# @name createQuestion
# POST {{baseUrl}}/rooms/{{roomId}}/questions
POST {{baseUrl}}/rooms/0dbc2f98-4968-44be-4fdb-f399737e5e21/questions
Content-Type: application/json

{
  "question": "O que estava testando"
}